### ISSUE TITLE
Local/"installable" version.

### ISSUE THREAD

**Issue by pul53gh** [ryohey/signal#321]
Some people like me just aren't a fan of web apps. It'd be cool to have a local version of the app for Windows or Mac for when I wanna work on projects but don't have access to internet, or would just rather not deal with Chrome. Other DAWs and midi editors just aren't as straightforward or aesthetically pleasing as signal is, so it'd be nice if there were an option who want something both straightforward and accessible without all the fuss.

**Comment by ryohey** [comment]
Hi @pul53gh @hidude562 I have launched a mac app store version! please check it out https://apps.apple.com/us/app/signal-midi-editor/id6499489458

**Comment by pul53gh** [comment]
Sorry man but not for $20 lmao

**Comment by ryohey** [comment]
@pul53gh No problem! Thanks for taking a look! I have made this a paid app because I have to pay Apple $100 annually for the distribution of the app.
However, all the source code is publicly available, so you can even build it with your own Apple Developer account and get the same thing.
Just curious, I can offer a sale, how much would you be willing to pay?

**Comment by pul53gh** [comment]
I’m only in a position to pay like $5 or $10 for something like that right
now. I didn’t know Apple charged for distribution, that kind of sucks.

**Comment by ryohey** [comment]
@pul53gh Hello! In response to your feedback, we are having a $9.99 sale to celebrate the launch, and it ends 6/30, so be sure to check it out. https://apps.apple.com/us/app/signal-midi-editor/id6499489458
